services:
  influxdb:
    image: influxdb:2.7-alpine
    ports: ["8086:8086"]
    networks: monitoring

    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_ORG: enphase
      DOCKER_INFLUXDB_INIT_BUCKET: solar
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb_admin_password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb_admin_token

    secrets:
      - influxdb_admin_password
      - influxdb_admin_token

    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro   # custom init script(s)
      - influxdb-data:/var/lib/influxdb2        # durable DB storage
      - token-volume:/token                     # writer token output

    healthcheck:
      test: ["CMD", "sh", "-c", "[ -f /token/influxdb_write.token ] && influx ping --host http://localhost:8086"]
      interval: 10s
      timeout: 3s
      retries: 5

  grafana:
    image: grafana/grafana-oss:12.0.0
    depends_on:
      influxdb:
        condition: service_healthy
    ports: ["3000:3000"]
    networks: monitoring

    volumes:
      - grafana-data:/var/lib/grafana

  ingestor:
    build:
      context: .
      dockerfile: Dockerfile
    networks: monitoring
    restart: unless-stopped
    working_dir: /app
    depends_on:
      influxdb:
        condition: service_healthy

    env_file: [.env]
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_ORG: enphase
      INFLUXDB_BUCKET: solar

    volumes:
      - token-volume:/token:ro                  # read the generated writer token

    entrypoint:
      - sh
      - -c
      - |
        # Wait until writer token appears (init script finishes)
        while [ ! -f /token/influxdb_write.token ]; do sleep 2; done
        export INFLUXDB_TOKEN=$(cat /token/influxdb_write.token)
        exec python main.py

  tailscale:
    image: tailscale/tailscale:latest
    container_name: ts-grafana
    network_mode: service:grafana
    hostname: grafana
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR: /var/lib/tailscale
    volumes:
      - tailscale-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

networks:
  monitoring:

volumes:
  influxdb-data:
  grafana-data:
  token-volume:                                 # holds the writer token
  tailscale-state:

secrets:
  influxdb_admin_password:
    file: secrets/influxdb_admin_password.txt
  influxdb_admin_token:
    file: secrets/influxdb_admin_token.txt
