name: Push to Cloud Source Repository

on:
  push:
    branches: [ main, google-cloud ]

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  CSR_NAME:    ${{ secrets.CSR_NAME }}    # your Cloud Source Repo name

jobs:
  sync-to-gcp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP using Workload Identity
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          export_default_credentials: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply (Cloud Source Repo)
        run: terraform apply -target=module.sourcerepo --auto-approve
        working-directory: terraform

      - name: Add GCP remote
        run: |
          git remote add google \
            https://source.developers.google.com/p/${GCP_PROJECT}/r/${CSR_NAME}

      - name: Push to Cloud Source Repositories
        run: |
          git push --all google --force